version: '3.5'
services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb_root_password
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongodb_root_username
      MONGO_INITDB_DATABASE: FH
      MONGO_USERNAME_FILE: /run/secrets/mongodb_username
      MONGO_PASSWORD_FILE: /run/secrets/mongodb_password
      MONGO_DATABASE: parrot
    secrets:
        - mongodb_root_password
        - mongodb_root_username
        - mongodb_password
        - mongodb_username
    ports:
      - "27017:27017"
    networks:
      - petbot

  service_collect:
    build: './service_collect/'
    depends_on:
      - mongo
    networks:
      - petbot

  service_get:
    build: './service_get/'
    depends_on:
      - mongo
    networks:
      - petbot

  service_bot:
    restart: on-failure
    build: './service_bot/'
    networks:
      - petbot

networks:
  petbot:
    driver: bridge

secrets:
  mongodb_root_password:
    file: ./mongodb/.mongodb_root_password
  mongodb_root_username:
    file: ./mongodb/.mongodb_root_username
  mongodb_password:
    file: ./mongodb/.mongodb_password
  mongodb_username:
    file: ./mongodb/.mongodb_username